### ISSUE TITLE
Inclusion into the official F-Droid repository

### ISSUE THREAD

**Issue by kevATin** [AnonymousMessenger/AnonymousMessenger#2]
I've already seen that you have a self hosted F-Droid repo for the app.
Are there any plans for applying the app for inclusion into the official F-Droid repo?

**Comment by DrXtreme** [comment]
Yes we are having difficulty with the building script for the fdroid software, once we get that sorted out we will be included.

**Comment by DrXtreme** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1616

**Comment by DrXtreme** [comment]
Version 0.8.3 has been built with the F-droid system and will be available through F-droid in a few days
