### ISSUE TITLE
Groups & Contact List Directory ?

### ISSUE THREAD

**Issue by xyz-nobody** [AnonymousMessenger/AnonymousMessenger#3]
I like the app which works perfectly (except the alpha version of the calls because it lags too much)

Would it be possible to consider creating groups?

Have you thought about creating a directory of users that could be hosted on its own phone or a small linux server? The idea is to have a directory that can be shared between friends (not a public directory)

**Comment by DrXtreme** [comment]
We will add a feature for sharing contacts, as for the user directory that feature is still in the planning phase.
